mysql:
 ip: 127.0.0.1
 port: 3306
 user: root
 password: 123456
 port_range:
  start: 8000
  end: 8100
 schema: ldogimage
oatpp:
 ip: localhost
 port: 8000
 port_range:
  start: 8000
  end: 
image:
#大小单位为字节/byte,时间单位为秒/s
 save_path: F:/ldog_images/images
 tmp_path: F:/ldog_images/tmp
 single_event_duration: 3600
 max_size: 104857600
 chunk_size: 10485760