#include"oatpp/parser/json/mapping/ObjectMapper.hpp"
#include"oatpp/web/server/HttpConnectionHandler.hpp"
#include"oatpp/network/Server.hpp"
#include"oatpp/network/tcp/server/ConnectionProvider.hpp"
#include"oatpp/web/server/AsyncHttpConnectionHandler.hpp"
#include"oatpp/web/server/api/ApiController.hpp"
#include"oatpp/core/macro/component.hpp"
#include"oatpp/core/macro/codegen.hpp"
#include"oatpp/core/data/stream/FileStream.hpp"
#include"oatpp/web/mime/multipart/InMemoryDataProvider.hpp"
#include"oatpp/web/mime/multipart/FileProvider.hpp"
#include "oatpp/web/mime/multipart/Reader.hpp"
#include "oatpp/web/mime/multipart/PartList.hpp"
#include "oatpp/web/protocol/http/outgoing/StreamingBody.hpp"